### PR TITLE
Add pip requirements

### PR DESCRIPTION
**Pull request by fuzzmz**
Add pip requirements file for using `update_icon_list.py`. This should be merged after #7

### CODE REVIEW

**Comment by bmcorser** [comment]
These aren't strictly requirements of using the plugin. They should live in a separate requirements file (ie. `scrips/requirements.txt`).

**Comment by bmcorser** [comment]
❗️ did you just read my mind?

**Comment by fuzzmz** [comment]
@bmcorser :8ball: (but it was like that since the beginning)

**Comment by bmcorser** [comment]
`:)`

**Pull request merged**
